"""Database abstractions and connectivity for Atlas AI."""

from app.db.entity_persister import (
    EntityPersistenceResult,
    EntityPersister,
    Neo4jPersistenceError,
    entity_to_properties,
    get_entity_merge_cypher,
    persist_entities,
)
from app.db.neo4j import (
    Neo4jConnectionError,
    close_driver,
    get_driver,
    get_neo4j_session,
    init_driver,
    set_driver,
    verify_connectivity,
)
from app.db.relationship_persister import (
    Neo4jRelationshipPersistenceError,
    RelationshipPersistenceResult,
    RelationshipPersister,
    get_relationship_merge_cypher,
    persist_relationships,
    relationship_to_properties,
)
from app.db.schema import (
    NODE_SCHEMAS,
    P0_CONSTRAINTS,
    P0_INDEXES,
    RELATIONSHIP_PATTERNS,
    ConstraintDefinition,
    IndexDefinition,
    Neo4jSchemaError,
    NodeLabel,
    NodePropertySchema,
    RelationshipPatternSchema,
    get_all_schema_statements,
    get_constraint_statements,
    get_index_statements,
    get_schema_constraints,
    get_schema_indexes,
    init_schema,
)

__all__ = [
    "ConstraintDefinition",
    "EntityPersistenceResult",
    "EntityPersister",
    "IndexDefinition",
    "NODE_SCHEMAS",
    "Neo4jConnectionError",
    "Neo4jPersistenceError",
    "Neo4jRelationshipPersistenceError",
    "Neo4jSchemaError",
    "NodeLabel",
    "NodePropertySchema",
    "P0_CONSTRAINTS",
    "P0_INDEXES",
    "RELATIONSHIP_PATTERNS",
    "RelationshipPatternSchema",
    "RelationshipPersistenceResult",
    "RelationshipPersister",
    "close_driver",
    "entity_to_properties",
    "get_all_schema_statements",
    "get_constraint_statements",
    "get_driver",
    "get_entity_merge_cypher",
    "get_index_statements",
    "get_neo4j_session",
    "get_relationship_merge_cypher",
    "get_schema_constraints",
    "get_schema_indexes",
    "init_driver",
    "init_schema",
    "persist_entities",
    "persist_relationships",
    "relationship_to_properties",
    "set_driver",
    "verify_connectivity",
]


